parameters:
#    watcher_twitter_aggregator.example.class: Watcher\TwitterAggregatorBundle\Example

services:
#    watcher_twitter_aggregator.example:
#        class: %watcher_twitter_aggregator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
